import{a as x}from"./assets/vendor-a2e8d7fa.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&a(r)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();const p=document.querySelector(".exercises-list"),m=document.querySelector(".exercises-list-pages");let d=1,v=8,g="Muscles";const L=document.querySelectorAll(".exercises-button");[...L].map((i,s)=>{s===0&&i.classList.add("exercises-button-active"),i.addEventListener("click",y)});async function h(i,s,c,a,e,t){let r={page:c,limit:a};e?(r[s]=e,r.keyword=t):r.filter=s;let f=new URLSearchParams(r).toString();try{return(await x.get(`https://energyflow.b.goit.study/api/${i}?${f}`)).data}catch(l){console.log(l)}}y();function y(i){if(d=1,i){const e=i.target;if(e.classList.contains("exercises-button-active"))return;g=e.dataset.name,document.querySelector(".exercises-button-active").classList.remove("exercises-button-active"),e.classList.add("exercises-button-active")}s();async function s(){const e=await h("filters",g,d,v).then(t=>t).catch(t=>console.log(t));c(e.results,e.totalPages)}function c(e,t){let r=e.reduce((n,{filter:o,imgUrl:b,name:u})=>n+=`<li class="exercises-item" data-type="${u}" style="background-image: linear-gradient(
      0deg,
      rgba(16, 16, 16, 0.7) 0%,
      rgba(16, 16, 16, 0.7) 100%
    ),url(${b}); ">
          <p class="exercises-item-text" data-type="${u}">${u}</p>
          <p class="exercises-item-text-second" data-type="${u}">${o}</p>
        </li>`,"");p.innerHTML=r,p.addEventListener("click",a),(!m.textContent||g!==document.querySelector(".exercises-pages-button").dataset.type)&&f();function f(){let n="";for(let o=1;o<t+1;o++)n+=`<li>
          <button class="exercises-pages-button" data-number="${o}" data-type="${g}">${o}</button>
        </li>`;m.innerHTML=n,document.querySelector(".exercises-pages-button").classList.add("select-pages-ative"),m.addEventListener("click",l)}function l(n){if(d==n.target.dataset.number)return;document.querySelector(".select-pages-ative").classList.remove("select-pages-ative"),n.target.classList.add("select-pages-ative"),d=n.target.dataset.number,s()}}function a(e){p.removeEventListener("click",a),document.querySelector(".exercises-button-active").dataset.name,e.target.dataset.type,console.log(e.target.dataset.type)}}
//# sourceMappingURL=commonHelpers.js.map
